version: '3'
services:
  web:
    build: . 
    image: odoo:12.1
    restart: always
    depends_on:
      - db
    volumes:
      - ./odoo_data:/var/lib/odoo:rw,z
      - ${ODOO_ADDONS}:/mnt/extra-addons:ro
      - ${ODOO_CONF}:/etc/odoo:ro
    ports:
      - "${ODOO_PORT}"

  db:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=${PGDATA}
    volumes:
      - ./odoo-db-data:/var/lib/postgresql/data/pgdata:rw

