version: '3'
services:
  web:
    build: . 
    image: odoo:12.1
    restart: always
    depends_on:
      - db
    volumes:
      - odoo_data:/var/lib/odoo:rw,z
      - ${ODOO_ADDONS:-./addons}:/mnt/extra-addons:ro,z
      - ${ODOO_CONF:-./config}:/etc/odoo:ro,z
    ports:
      - "${ODOO_PORT:-8069}"

  db:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-odoo}
      - POSTGRES_USER=${POSTGRES_USER:-odoo}
      - PGDATA=${PGDATA:-/var/lib/postgresql/data/pgdata}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata:rw,Z
volumes:
  odoo_data:
  odoo-db-data:
  odoo_addons:
